name: CI
# env:
#   JULIA_CPU_TARGET: "generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)"
on:
  push:
    branches:
      - main
    tags: ['v*']
  pull_request:
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'min'
          - '1'
          # - 'pre'
        os:
          - ubuntu-latest
          # - macOS-latest
          # - windows-latest
        arch:
          - 'default'
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 2 # Allows codecov to determine the correct commit SHA in the case of a merge commit.
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v3
        # with:
        #   cache-compiled: false
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: lcov.info
          fail_ci_if_error: false
  aqua:
    name: Aqua tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: '1'
      - uses: julia-actions/julia-buildpkg@v1
      - run: julia -e 'using Pkg; Pkg.add("Aqua")'
      - run: julia --project=@. -e 'using Aqua, CrowdPhot; Aqua.test_all(CrowdPhot, ambiguities=false)'
  docs:
    name: Documentation
    timeout-minutes: 60
    if: >
      github.event_name != 'push' ||
      !contains(github.event.head_commit.message, '[skip docs]')
    runs-on: ubuntu-latest
    permissions:
      actions: write # needed to allow julia-actions/cache to proactively delete old caches that it has created
      contents: write
      statuses: write
      pull-requests: read # to allow push previews to create PR comments
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: '1'
      - uses: julia-actions/cache@v3
        # with:
        #   cache-compiled: false
      - uses: julia-actions/julia-buildpkg@v1
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
